import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { baseStyles, colors } from './base-styles';

interface BusinessPlanData {
  ideaTitle: string;
  ideaDescription: string;
  generatedAt: Date;
  tier: 'BASIC' | 'PRO' | 'FULL';

  // Executive Summary
  executiveSummary?: string;

  // Problem & Solution
  problemStatement?: string;
  solution?: string;
  uniqueValueProposition?: string;

  // Market Analysis
  targetMarket?: string;
  marketSize?: string;
  marketTrends?: string[];

  // Competitive Landscape
  competitors?: Array<{
    name: string;
    strengths: string;
    weaknesses: string;
  }>;
  competitiveAdvantage?: string;

  // Business Model
  revenueStreams?: string[];
  pricingStrategy?: string;
  costStructure?: string;

  // Go-to-Market
  marketingStrategy?: string;
  salesChannels?: string[];
  customerAcquisition?: string;

  // Financial Projections (PRO/FULL only)
  financialProjections?: {
    year1Revenue?: string;
    year2Revenue?: string;
    year3Revenue?: string;
    breakEvenPoint?: string;
  };

  // Team & Operations (FULL only)
  teamRequirements?: string[];
  milestones?: Array<{
    milestone: string;
    timeline: string;
  }>;

  // Scores
  scores?: {
    opportunity?: number;
    problem?: number;
    feasibility?: number;
    whyNow?: number;
  };
}

function Header({ title, ideaTitle, date }: { title: string; ideaTitle: string; date: Date }) {
  return (
    <View style={baseStyles.header}>
      <Text style={baseStyles.logo}>FORGE</Text>
      <Text style={baseStyles.reportTitle}>{title}</Text>
      <Text style={baseStyles.ideaTitle}>{ideaTitle}</Text>
      <Text style={baseStyles.generatedDate}>
        Generated on {date.toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        })}
      </Text>
    </View>
  );
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function Section({ title, children }: { title: string; children?: any }) {
  return (
    <View style={baseStyles.section}>
      <Text style={baseStyles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <View style={baseStyles.list}>
      {items.map((item, index) => (
        <View key={index} style={baseStyles.bulletPoint}>
          <Text style={baseStyles.bullet}>•</Text>
          <Text style={baseStyles.bulletText}>{item}</Text>
        </View>
      ))}
    </View>
  );
}

function ScoreCard({ label, value }: { label: string; value?: number }) {
  const displayValue = value ?? '--';
  return (
    <View style={baseStyles.scoreBox}>
      <Text style={baseStyles.scoreValue}>{displayValue}</Text>
      <Text style={baseStyles.scoreLabel}>{label}</Text>
    </View>
  );
}

function Footer({ pageNumber }: { pageNumber: number }) {
  return (
    <View style={baseStyles.footer} fixed>
      <Text style={baseStyles.footerText}>Generated by Forge AI</Text>
      <Text style={baseStyles.pageNumber}>Page {pageNumber}</Text>
    </View>
  );
}

export function BusinessPlanPDF({ data }: { data: BusinessPlanData }) {
  const isPro = data.tier === 'PRO' || data.tier === 'FULL';
  const isFull = data.tier === 'FULL';

  return (
    <Document>
      {/* Page 1: Executive Summary & Problem/Solution */}
      <Page size="A4" style={baseStyles.page}>
        <Header
          title="Business Plan"
          ideaTitle={data.ideaTitle}
          date={data.generatedAt}
        />

        {/* Scores Overview */}
        {data.scores && (
          <View style={baseStyles.scoreContainer}>
            <ScoreCard label="Opportunity" value={data.scores.opportunity} />
            <ScoreCard label="Problem Severity" value={data.scores.problem} />
            <ScoreCard label="Feasibility" value={data.scores.feasibility} />
            <ScoreCard label="Timing" value={data.scores.whyNow} />
          </View>
        )}

        <Section title="Executive Summary">
          <Text style={baseStyles.paragraph}>
            {data.executiveSummary || data.ideaDescription}
          </Text>
        </Section>

        <Section title="Problem Statement">
          <Text style={baseStyles.paragraph}>
            {data.problemStatement || 'Problem analysis pending research completion.'}
          </Text>
        </Section>

        <Section title="Proposed Solution">
          <Text style={baseStyles.paragraph}>
            {data.solution || 'Solution details pending research completion.'}
          </Text>
        </Section>

        {data.uniqueValueProposition && (
          <View style={baseStyles.highlightCard}>
            <Text style={baseStyles.label}>Unique Value Proposition</Text>
            <Text style={baseStyles.paragraph}>{data.uniqueValueProposition}</Text>
          </View>
        )}

        <Footer pageNumber={1} />
      </Page>

      {/* Page 2: Market Analysis */}
      <Page size="A4" style={baseStyles.page}>
        <Section title="Target Market">
          <Text style={baseStyles.paragraph}>
            {data.targetMarket || 'Market analysis pending.'}
          </Text>
        </Section>

        {data.marketSize && (
          <Section title="Market Size & Opportunity">
            <Text style={baseStyles.paragraph}>{data.marketSize}</Text>
          </Section>
        )}

        {data.marketTrends && data.marketTrends.length > 0 && (
          <Section title="Market Trends">
            <BulletList items={data.marketTrends} />
          </Section>
        )}

        {data.competitors && data.competitors.length > 0 && (
          <Section title="Competitive Landscape">
            {data.competitors.map((competitor, index) => (
              <View key={index} style={baseStyles.card}>
                <Text style={baseStyles.h3}>{competitor.name}</Text>
                <Text style={baseStyles.label}>Strengths</Text>
                <Text style={baseStyles.paragraph}>{competitor.strengths}</Text>
                <Text style={baseStyles.label}>Weaknesses</Text>
                <Text style={baseStyles.paragraph}>{competitor.weaknesses}</Text>
              </View>
            ))}
          </Section>
        )}

        {data.competitiveAdvantage && (
          <View style={baseStyles.successCard}>
            <Text style={baseStyles.label}>Your Competitive Advantage</Text>
            <Text style={baseStyles.paragraph}>{data.competitiveAdvantage}</Text>
          </View>
        )}

        <Footer pageNumber={2} />
      </Page>

      {/* Page 3: Business Model & Go-to-Market */}
      <Page size="A4" style={baseStyles.page}>
        <Section title="Business Model">
          {data.revenueStreams && data.revenueStreams.length > 0 && (
            <>
              <Text style={baseStyles.label}>Revenue Streams</Text>
              <BulletList items={data.revenueStreams} />
            </>
          )}

          {data.pricingStrategy && (
            <>
              <Text style={baseStyles.label}>Pricing Strategy</Text>
              <Text style={baseStyles.paragraph}>{data.pricingStrategy}</Text>
            </>
          )}

          {data.costStructure && (
            <>
              <Text style={baseStyles.label}>Cost Structure</Text>
              <Text style={baseStyles.paragraph}>{data.costStructure}</Text>
            </>
          )}
        </Section>

        <Section title="Go-to-Market Strategy">
          {data.marketingStrategy && (
            <Text style={baseStyles.paragraph}>{data.marketingStrategy}</Text>
          )}

          {data.salesChannels && data.salesChannels.length > 0 && (
            <>
              <Text style={baseStyles.label}>Sales Channels</Text>
              <BulletList items={data.salesChannels} />
            </>
          )}

          {data.customerAcquisition && (
            <>
              <Text style={baseStyles.label}>Customer Acquisition</Text>
              <Text style={baseStyles.paragraph}>{data.customerAcquisition}</Text>
            </>
          )}
        </Section>

        <Footer pageNumber={3} />
      </Page>

      {/* Page 4: Financial Projections (PRO/FULL only) */}
      {isPro && data.financialProjections && (
        <Page size="A4" style={baseStyles.page}>
          <Section title="Financial Projections">
            <View style={baseStyles.table}>
              <View style={baseStyles.tableHeader}>
                <Text style={[baseStyles.tableCellHeader, { width: '25%' }]}>Period</Text>
                <Text style={[baseStyles.tableCellHeader, { width: '75%' }]}>Projected Revenue</Text>
              </View>
              <View style={baseStyles.tableRow}>
                <Text style={[baseStyles.tableCell, { width: '25%' }]}>Year 1</Text>
                <Text style={[baseStyles.tableCell, { width: '75%' }]}>
                  {data.financialProjections.year1Revenue || 'TBD'}
                </Text>
              </View>
              <View style={baseStyles.tableRow}>
                <Text style={[baseStyles.tableCell, { width: '25%' }]}>Year 2</Text>
                <Text style={[baseStyles.tableCell, { width: '75%' }]}>
                  {data.financialProjections.year2Revenue || 'TBD'}
                </Text>
              </View>
              <View style={baseStyles.tableRow}>
                <Text style={[baseStyles.tableCell, { width: '25%' }]}>Year 3</Text>
                <Text style={[baseStyles.tableCell, { width: '75%' }]}>
                  {data.financialProjections.year3Revenue || 'TBD'}
                </Text>
              </View>
            </View>

            {data.financialProjections.breakEvenPoint && (
              <View style={baseStyles.highlightCard}>
                <Text style={baseStyles.label}>Break-Even Point</Text>
                <Text style={baseStyles.paragraph}>
                  {data.financialProjections.breakEvenPoint}
                </Text>
              </View>
            )}
          </Section>

          <Footer pageNumber={4} />
        </Page>
      )}

      {/* Page 5: Team & Milestones (FULL only) */}
      {isFull && (
        <Page size="A4" style={baseStyles.page}>
          {data.teamRequirements && data.teamRequirements.length > 0 && (
            <Section title="Team Requirements">
              <BulletList items={data.teamRequirements} />
            </Section>
          )}

          {data.milestones && data.milestones.length > 0 && (
            <Section title="Key Milestones">
              <View style={baseStyles.table}>
                <View style={baseStyles.tableHeader}>
                  <Text style={[baseStyles.tableCellHeader, { width: '70%' }]}>Milestone</Text>
                  <Text style={[baseStyles.tableCellHeader, { width: '30%' }]}>Timeline</Text>
                </View>
                {data.milestones.map((milestone, index) => (
                  <View key={index} style={baseStyles.tableRow}>
                    <Text style={[baseStyles.tableCell, { width: '70%' }]}>
                      {milestone.milestone}
                    </Text>
                    <Text style={[baseStyles.tableCell, { width: '30%' }]}>
                      {milestone.timeline}
                    </Text>
                  </View>
                ))}
              </View>
            </Section>
          )}

          <Footer pageNumber={5} />
        </Page>
      )}
    </Document>
  );
}

export default BusinessPlanPDF;
