import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { baseStyles } from './base-styles';

interface CompetitiveAnalysisData {
  ideaTitle: string;
  ideaDescription: string;
  generatedAt: Date;
  tier: 'BASIC' | 'PRO' | 'FULL';

  // Market Overview
  marketOverview?: string;
  industryTrends?: string[];

  // Competitors
  competitors?: Array<{
    name: string;
    description: string;
    website?: string;
    pricing?: string;
    strengths: string[];
    weaknesses: string[];
    targetAudience?: string;
  }>;

  // SWOT Analysis
  swot?: {
    strengths: string[];
    weaknesses: string[];
    opportunities: string[];
    threats: string[];
  };

  // Competitive Advantages
  competitiveAdvantages?: string[];
  differentiators?: string[];

  // Market Gaps (PRO/FULL)
  marketGaps?: string[];
  underservedSegments?: string[];

  // Strategic Recommendations (FULL)
  strategicRecommendations?: string[];
  competitiveStrategy?: string;
}

function Header({ title, ideaTitle, date }: { title: string; ideaTitle: string; date: Date }) {
  return (
    <View style={baseStyles.header}>
      <Text style={baseStyles.logo}>FORGE</Text>
      <Text style={baseStyles.reportTitle}>{title}</Text>
      <Text style={baseStyles.ideaTitle}>{ideaTitle}</Text>
      <Text style={baseStyles.generatedDate}>
        Generated on {date.toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        })}
      </Text>
    </View>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={baseStyles.section}>
      <Text style={baseStyles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <View style={baseStyles.list}>
      {items.map((item, index) => (
        <View key={index} style={baseStyles.bulletPoint}>
          <Text style={baseStyles.bullet}>•</Text>
          <Text style={baseStyles.bulletText}>{item}</Text>
        </View>
      ))}
    </View>
  );
}

function Footer({ pageNumber }: { pageNumber: number }) {
  return (
    <View style={baseStyles.footer} fixed>
      <Text style={baseStyles.footerText}>Generated by Forge AI</Text>
      <Text style={baseStyles.pageNumber}>Page {pageNumber}</Text>
    </View>
  );
}

export function CompetitiveAnalysisPDF({ data }: { data: CompetitiveAnalysisData }) {
  const isPro = data.tier === 'PRO' || data.tier === 'FULL';
  const isFull = data.tier === 'FULL';

  return (
    <Document>
      {/* Page 1: Market Overview & Industry Trends */}
      <Page size="A4" style={baseStyles.page}>
        <Header
          title="Competitive Analysis"
          ideaTitle={data.ideaTitle}
          date={data.generatedAt}
        />

        <Section title="Market Overview">
          <Text style={baseStyles.paragraph}>
            {data.marketOverview || 'Market overview pending research completion.'}
          </Text>
        </Section>

        {data.industryTrends && data.industryTrends.length > 0 && (
          <Section title="Industry Trends">
            <BulletList items={data.industryTrends} />
          </Section>
        )}

        <Footer pageNumber={1} />
      </Page>

      {/* Page 2-3: Competitor Profiles */}
      {data.competitors && data.competitors.length > 0 && (
        <Page size="A4" style={baseStyles.page}>
          <Section title="Competitor Profiles">
            {data.competitors.slice(0, 2).map((competitor, index) => (
              <View key={index} style={baseStyles.card}>
                <Text style={baseStyles.h3}>{competitor.name}</Text>
                {competitor.website && (
                  <Text style={[baseStyles.paragraph, { fontSize: 10, color: '#6366f1' }]}>
                    {competitor.website}
                  </Text>
                )}
                <Text style={baseStyles.paragraph}>{competitor.description}</Text>

                {competitor.pricing && (
                  <>
                    <Text style={baseStyles.label}>Pricing</Text>
                    <Text style={baseStyles.paragraph}>{competitor.pricing}</Text>
                  </>
                )}

                {competitor.targetAudience && (
                  <>
                    <Text style={baseStyles.label}>Target Audience</Text>
                    <Text style={baseStyles.paragraph}>{competitor.targetAudience}</Text>
                  </>
                )}

                <View style={{ flexDirection: 'row', marginTop: 8 }}>
                  <View style={{ flex: 1, marginRight: 8 }}>
                    <Text style={[baseStyles.label, { color: '#22c55e' }]}>Strengths</Text>
                    <BulletList items={competitor.strengths} />
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text style={[baseStyles.label, { color: '#ef4444' }]}>Weaknesses</Text>
                    <BulletList items={competitor.weaknesses} />
                  </View>
                </View>
              </View>
            ))}
          </Section>

          <Footer pageNumber={2} />
        </Page>
      )}

      {/* Additional competitors page if needed */}
      {data.competitors && data.competitors.length > 2 && (
        <Page size="A4" style={baseStyles.page}>
          <Section title="Competitor Profiles (Continued)">
            {data.competitors.slice(2, 4).map((competitor, index) => (
              <View key={index} style={baseStyles.card}>
                <Text style={baseStyles.h3}>{competitor.name}</Text>
                {competitor.website && (
                  <Text style={[baseStyles.paragraph, { fontSize: 10, color: '#6366f1' }]}>
                    {competitor.website}
                  </Text>
                )}
                <Text style={baseStyles.paragraph}>{competitor.description}</Text>

                <View style={{ flexDirection: 'row', marginTop: 8 }}>
                  <View style={{ flex: 1, marginRight: 8 }}>
                    <Text style={[baseStyles.label, { color: '#22c55e' }]}>Strengths</Text>
                    <BulletList items={competitor.strengths} />
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text style={[baseStyles.label, { color: '#ef4444' }]}>Weaknesses</Text>
                    <BulletList items={competitor.weaknesses} />
                  </View>
                </View>
              </View>
            ))}
          </Section>

          <Footer pageNumber={3} />
        </Page>
      )}

      {/* SWOT Analysis */}
      {data.swot && (
        <Page size="A4" style={baseStyles.page}>
          <Section title="SWOT Analysis">
            <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
              <View style={{ width: '50%', paddingRight: 8, marginBottom: 16 }}>
                <View style={[baseStyles.card, { backgroundColor: '#f0fdf4' }]}>
                  <Text style={[baseStyles.h3, { color: '#22c55e' }]}>Strengths</Text>
                  <BulletList items={data.swot.strengths} />
                </View>
              </View>
              <View style={{ width: '50%', paddingLeft: 8, marginBottom: 16 }}>
                <View style={[baseStyles.card, { backgroundColor: '#fef2f2' }]}>
                  <Text style={[baseStyles.h3, { color: '#ef4444' }]}>Weaknesses</Text>
                  <BulletList items={data.swot.weaknesses} />
                </View>
              </View>
              <View style={{ width: '50%', paddingRight: 8 }}>
                <View style={[baseStyles.card, { backgroundColor: '#f0f4ff' }]}>
                  <Text style={[baseStyles.h3, { color: '#6366f1' }]}>Opportunities</Text>
                  <BulletList items={data.swot.opportunities} />
                </View>
              </View>
              <View style={{ width: '50%', paddingLeft: 8 }}>
                <View style={[baseStyles.card, { backgroundColor: '#fff7ed' }]}>
                  <Text style={[baseStyles.h3, { color: '#f59e0b' }]}>Threats</Text>
                  <BulletList items={data.swot.threats} />
                </View>
              </View>
            </View>
          </Section>

          <Footer pageNumber={data.competitors && data.competitors.length > 2 ? 4 : 3} />
        </Page>
      )}

      {/* Competitive Advantages */}
      <Page size="A4" style={baseStyles.page}>
        {data.competitiveAdvantages && data.competitiveAdvantages.length > 0 && (
          <Section title="Your Competitive Advantages">
            {data.competitiveAdvantages.map((advantage, index) => (
              <View key={index} style={baseStyles.successCard}>
                <Text style={baseStyles.paragraph}>{advantage}</Text>
              </View>
            ))}
          </Section>
        )}

        {data.differentiators && data.differentiators.length > 0 && (
          <Section title="Key Differentiators">
            <BulletList items={data.differentiators} />
          </Section>
        )}

        <Footer pageNumber={data.competitors && data.competitors.length > 2 ? 5 : 4} />
      </Page>

      {/* Market Gaps (PRO/FULL) */}
      {isPro && (data.marketGaps || data.underservedSegments) && (
        <Page size="A4" style={baseStyles.page}>
          {data.marketGaps && data.marketGaps.length > 0 && (
            <Section title="Market Gaps & Opportunities">
              {data.marketGaps.map((gap, index) => (
                <View key={index} style={baseStyles.highlightCard}>
                  <Text style={baseStyles.paragraph}>{gap}</Text>
                </View>
              ))}
            </Section>
          )}

          {data.underservedSegments && data.underservedSegments.length > 0 && (
            <Section title="Underserved Market Segments">
              <BulletList items={data.underservedSegments} />
            </Section>
          )}

          <Footer pageNumber={data.competitors && data.competitors.length > 2 ? 6 : 5} />
        </Page>
      )}

      {/* Strategic Recommendations (FULL) */}
      {isFull && (data.strategicRecommendations || data.competitiveStrategy) && (
        <Page size="A4" style={baseStyles.page}>
          {data.competitiveStrategy && (
            <Section title="Recommended Competitive Strategy">
              <Text style={baseStyles.paragraph}>{data.competitiveStrategy}</Text>
            </Section>
          )}

          {data.strategicRecommendations && data.strategicRecommendations.length > 0 && (
            <Section title="Strategic Recommendations">
              {data.strategicRecommendations.map((rec, index) => (
                <View key={index} style={baseStyles.card}>
                  <Text style={baseStyles.paragraph}>
                    {index + 1}. {rec}
                  </Text>
                </View>
              ))}
            </Section>
          )}

          <Footer pageNumber={data.competitors && data.competitors.length > 2 ? 7 : 6} />
        </Page>
      )}
    </Document>
  );
}

export default CompetitiveAnalysisPDF;
