import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { baseStyles } from './base-styles';

interface PositioningData {
  ideaTitle: string;
  ideaDescription: string;
  generatedAt: Date;
  tier: 'BASIC' | 'PRO' | 'FULL';

  // Brand Positioning
  positioningStatement?: string;
  tagline?: string;
  brandVoice?: string;
  brandPersonality?: string[];

  // Target Audience
  targetAudience?: string;
  customerPersona?: {
    name: string;
    demographics: string;
    psychographics: string;
    painPoints: string[];
    goals: string[];
  };

  // Messaging Framework
  keyMessages?: string[];
  valuePillars?: Array<{
    pillar: string;
    description: string;
  }>;

  // Differentiation
  uniqueSellingPoints?: string[];
  competitivePositioning?: string;

  // Brand Identity (PRO/FULL)
  brandColors?: string[];
  visualStyle?: string;
  toneGuidelines?: string[];

  // Messaging by Channel (FULL)
  channelMessaging?: Array<{
    channel: string;
    headline: string;
    subheadline: string;
    cta: string;
  }>;
}

function Header({ title, ideaTitle, date }: { title: string; ideaTitle: string; date: Date }) {
  return (
    <View style={baseStyles.header}>
      <Text style={baseStyles.logo}>FORGE</Text>
      <Text style={baseStyles.reportTitle}>{title}</Text>
      <Text style={baseStyles.ideaTitle}>{ideaTitle}</Text>
      <Text style={baseStyles.generatedDate}>
        Generated on {date.toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        })}
      </Text>
    </View>
  );
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function Section({ title, children }: { title: string; children?: any }) {
  return (
    <View style={baseStyles.section}>
      <Text style={baseStyles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <View style={baseStyles.list}>
      {items.map((item, index) => (
        <View key={index} style={baseStyles.bulletPoint}>
          <Text style={baseStyles.bullet}>•</Text>
          <Text style={baseStyles.bulletText}>{item}</Text>
        </View>
      ))}
    </View>
  );
}

function Footer({ pageNumber }: { pageNumber: number }) {
  return (
    <View style={baseStyles.footer} fixed>
      <Text style={baseStyles.footerText}>Generated by Forge AI</Text>
      <Text style={baseStyles.pageNumber}>Page {pageNumber}</Text>
    </View>
  );
}

export function PositioningPDF({ data }: { data: PositioningData }) {
  const isPro = data.tier === 'PRO' || data.tier === 'FULL';
  const isFull = data.tier === 'FULL';

  return (
    <Document>
      {/* Page 1: Positioning Statement & Brand Voice */}
      <Page size="A4" style={baseStyles.page}>
        <Header
          title="Brand Positioning"
          ideaTitle={data.ideaTitle}
          date={data.generatedAt}
        />

        <Section title="Positioning Statement">
          <View style={baseStyles.highlightCard}>
            <Text style={baseStyles.paragraph}>
              {data.positioningStatement || 'Positioning statement pending research completion.'}
            </Text>
          </View>
        </Section>

        {data.tagline && (
          <Section title="Tagline">
            <View style={baseStyles.card}>
              <Text style={[baseStyles.h2, { textAlign: 'center', color: '#6366f1' }]}>
                "{data.tagline}"
              </Text>
            </View>
          </Section>
        )}

        {data.brandVoice && (
          <Section title="Brand Voice">
            <Text style={baseStyles.paragraph}>{data.brandVoice}</Text>
          </Section>
        )}

        {data.brandPersonality && data.brandPersonality.length > 0 && (
          <Section title="Brand Personality">
            <BulletList items={data.brandPersonality} />
          </Section>
        )}

        <Footer pageNumber={1} />
      </Page>

      {/* Page 2: Target Audience */}
      <Page size="A4" style={baseStyles.page}>
        <Section title="Target Audience">
          <Text style={baseStyles.paragraph}>
            {data.targetAudience || 'Target audience analysis pending.'}
          </Text>
        </Section>

        {data.customerPersona && (
          <Section title="Ideal Customer Persona">
            <View style={baseStyles.card}>
              <Text style={baseStyles.h3}>{data.customerPersona.name}</Text>

              <Text style={baseStyles.label}>Demographics</Text>
              <Text style={baseStyles.paragraph}>{data.customerPersona.demographics}</Text>

              <Text style={baseStyles.label}>Psychographics</Text>
              <Text style={baseStyles.paragraph}>{data.customerPersona.psychographics}</Text>

              <Text style={baseStyles.label}>Pain Points</Text>
              <BulletList items={data.customerPersona.painPoints} />

              <Text style={baseStyles.label}>Goals</Text>
              <BulletList items={data.customerPersona.goals} />
            </View>
          </Section>
        )}

        <Footer pageNumber={2} />
      </Page>

      {/* Page 3: Messaging Framework */}
      <Page size="A4" style={baseStyles.page}>
        {data.keyMessages && data.keyMessages.length > 0 && (
          <Section title="Key Messages">
            {data.keyMessages.map((message, index) => (
              <View key={index} style={baseStyles.highlightCard}>
                <Text style={baseStyles.paragraph}>{message}</Text>
              </View>
            ))}
          </Section>
        )}

        {data.valuePillars && data.valuePillars.length > 0 && (
          <Section title="Value Pillars">
            {data.valuePillars.map((pillar, index) => (
              <View key={index} style={baseStyles.card}>
                <Text style={baseStyles.h3}>{pillar.pillar}</Text>
                <Text style={baseStyles.paragraph}>{pillar.description}</Text>
              </View>
            ))}
          </Section>
        )}

        <Footer pageNumber={3} />
      </Page>

      {/* Page 4: Differentiation */}
      <Page size="A4" style={baseStyles.page}>
        {data.uniqueSellingPoints && data.uniqueSellingPoints.length > 0 && (
          <Section title="Unique Selling Points">
            <BulletList items={data.uniqueSellingPoints} />
          </Section>
        )}

        {data.competitivePositioning && (
          <Section title="Competitive Positioning">
            <Text style={baseStyles.paragraph}>{data.competitivePositioning}</Text>
          </Section>
        )}

        <Footer pageNumber={4} />
      </Page>

      {/* Page 5: Brand Identity (PRO/FULL) */}
      {isPro && (
        <Page size="A4" style={baseStyles.page}>
          <Section title="Brand Identity Guidelines">
            {data.visualStyle && (
              <>
                <Text style={baseStyles.label}>Visual Style</Text>
                <Text style={baseStyles.paragraph}>{data.visualStyle}</Text>
              </>
            )}

            {data.brandColors && data.brandColors.length > 0 && (
              <>
                <Text style={baseStyles.label}>Brand Colors</Text>
                <BulletList items={data.brandColors} />
              </>
            )}

            {data.toneGuidelines && data.toneGuidelines.length > 0 && (
              <>
                <Text style={baseStyles.label}>Tone Guidelines</Text>
                <BulletList items={data.toneGuidelines} />
              </>
            )}
          </Section>

          <Footer pageNumber={5} />
        </Page>
      )}

      {/* Page 6: Channel Messaging (FULL) */}
      {isFull && data.channelMessaging && data.channelMessaging.length > 0 && (
        <Page size="A4" style={baseStyles.page}>
          <Section title="Messaging by Channel">
            {data.channelMessaging.map((channel, index) => (
              <View key={index} style={baseStyles.card}>
                <Text style={baseStyles.h3}>{channel.channel}</Text>
                <Text style={baseStyles.label}>Headline</Text>
                <Text style={baseStyles.paragraph}>{channel.headline}</Text>
                <Text style={baseStyles.label}>Subheadline</Text>
                <Text style={baseStyles.paragraph}>{channel.subheadline}</Text>
                <Text style={baseStyles.label}>Call to Action</Text>
                <Text style={[baseStyles.paragraph, { color: '#6366f1', fontWeight: 'bold' }]}>
                  {channel.cta}
                </Text>
              </View>
            ))}
          </Section>

          <Footer pageNumber={6} />
        </Page>
      )}
    </Document>
  );
}

export default PositioningPDF;
