import type { TemplateDefinition } from '@forge/shared';

export const ecommerceTemplate: TemplateDefinition = {
  slug: 'ecommerce',
  name: 'E-commerce',
  description: 'Online retail with COGS, inventory, shipping, and marketplace fees',
  category: 'RETAIL',
  assumptions: {
    beginner: [
      { key: 'monthly_orders', name: 'Monthly Orders', valueType: 'NUMBER', default: 500 },
      { key: 'avg_order_value', name: 'Average Order Value', valueType: 'CURRENCY', unit: '$', default: 65 },
      { key: 'cogs_pct', name: 'COGS (% of Revenue)', valueType: 'PERCENTAGE', unit: '%', default: 40 },
      { key: 'shipping_cost_per_order', name: 'Avg Shipping Cost/Order', valueType: 'CURRENCY', unit: '$', default: 8 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'marketing_budget', name: 'Monthly Marketing Budget', valueType: 'CURRENCY', unit: '$', default: 2000 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 30000 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 8 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
    ],
    standard: [
      { key: 'monthly_orders', name: 'Monthly Orders', valueType: 'NUMBER', default: 500 },
      { key: 'avg_order_value', name: 'Average Order Value', valueType: 'CURRENCY', unit: '$', default: 65 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 8 },
      { key: 'cogs_pct', name: 'COGS (% of Revenue)', valueType: 'PERCENTAGE', unit: '%', default: 40 },
      { key: 'shipping_cost_per_order', name: 'Avg Shipping Cost/Order', valueType: 'CURRENCY', unit: '$', default: 8 },
      { key: 'return_rate', name: 'Return Rate', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'payment_processing_pct', name: 'Payment Processing (%)', valueType: 'PERCENTAGE', unit: '%', default: 2.9 },
      { key: 'marketplace_fee_pct', name: 'Marketplace Fee (%)', valueType: 'PERCENTAGE', unit: '%', default: 0 },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 2 },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 50000 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'marketing_budget', name: 'Monthly Marketing Budget', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'cac', name: 'Customer Acquisition Cost', valueType: 'CURRENCY', unit: '$', default: 25 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 30000 },
      { key: 'starting_inventory', name: 'Starting Inventory Value', valueType: 'CURRENCY', unit: '$', default: 15000 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
      { key: 'accounts_receivable_days', name: 'AR Days', valueType: 'NUMBER', default: 5 },
      { key: 'accounts_payable_days', name: 'AP Days', valueType: 'NUMBER', default: 30 },
      { key: 'inventory_turns', name: 'Inventory Turns/Year', valueType: 'NUMBER', default: 6 },
    ],
    expert: [
      { key: 'monthly_orders', name: 'Monthly Orders', valueType: 'NUMBER', default: 500 },
      { key: 'avg_order_value', name: 'Average Order Value', valueType: 'CURRENCY', unit: '$', default: 65 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 8 },
      { key: 'repeat_purchase_rate', name: 'Repeat Purchase Rate', valueType: 'PERCENTAGE', unit: '%', default: 30 },
      { key: 'cogs_pct', name: 'COGS (% of Revenue)', valueType: 'PERCENTAGE', unit: '%', default: 40 },
      { key: 'shipping_cost_per_order', name: 'Avg Shipping Cost/Order', valueType: 'CURRENCY', unit: '$', default: 8 },
      { key: 'return_rate', name: 'Return Rate', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'return_processing_cost', name: 'Return Processing Cost', valueType: 'CURRENCY', unit: '$', default: 5 },
      { key: 'payment_processing_pct', name: 'Payment Processing (%)', valueType: 'PERCENTAGE', unit: '%', default: 2.9 },
      { key: 'marketplace_fee_pct', name: 'Marketplace Fee (%)', valueType: 'PERCENTAGE', unit: '%', default: 0 },
      { key: 'packaging_cost_per_order', name: 'Packaging Cost/Order', valueType: 'CURRENCY', unit: '$', default: 2 },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 3 },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 50000 },
      { key: 'warehouse_cost', name: 'Monthly Warehouse Cost', valueType: 'CURRENCY', unit: '$', default: 2000 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'marketing_budget', name: 'Monthly Marketing Budget', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'cac', name: 'Customer Acquisition Cost', valueType: 'CURRENCY', unit: '$', default: 25 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 30000 },
      { key: 'starting_inventory', name: 'Starting Inventory Value', valueType: 'CURRENCY', unit: '$', default: 15000 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
      { key: 'accounts_receivable_days', name: 'AR Days', valueType: 'NUMBER', default: 5 },
      { key: 'accounts_payable_days', name: 'AP Days', valueType: 'NUMBER', default: 30 },
      { key: 'inventory_turns', name: 'Inventory Turns/Year', valueType: 'NUMBER', default: 6 },
      { key: 'shrinkage_pct', name: 'Inventory Shrinkage (%)', valueType: 'PERCENTAGE', unit: '%', default: 1 },
    ],
  },
  lineItems: {
    pl: [
      { key: 'revenue', name: 'Revenue', children: ['gross_revenue', 'returns'], isTotal: true },
      { key: 'gross_revenue', name: 'Gross Revenue', formula: 'monthly_orders * avg_order_value' },
      { key: 'returns', name: 'Returns & Refunds', formula: '-(gross_revenue * return_rate / 100)' },
      { key: 'cogs', name: 'Cost of Goods Sold', formula: 'gross_revenue * cogs_pct / 100' },
      { key: 'shipping_costs', name: 'Shipping Costs', formula: 'monthly_orders * shipping_cost_per_order' },
      { key: 'payment_processing', name: 'Payment Processing', formula: 'gross_revenue * payment_processing_pct / 100' },
      { key: 'marketplace_fees', name: 'Marketplace Fees', formula: 'gross_revenue * marketplace_fee_pct / 100' },
      { key: 'gross_profit', name: 'Gross Profit', formula: 'revenue - cogs - shipping_costs - payment_processing - marketplace_fees', isSubtotal: true },
      { key: 'salaries', name: 'Salaries & Wages', formula: 'headcount * avg_salary / 12' },
      { key: 'marketing', name: 'Marketing & Advertising', formula: 'marketing_budget' },
      { key: 'opex_other', name: 'Other Operating Expenses', formula: 'monthly_opex' },
      { key: 'total_opex', name: 'Total Operating Expenses', formula: 'salaries + marketing + opex_other', isSubtotal: true },
      { key: 'ebitda', name: 'EBITDA', formula: 'gross_profit - total_opex', isSubtotal: true },
      { key: 'depreciation', name: 'Depreciation', formula: '0' },
      { key: 'ebit', name: 'EBIT', formula: 'ebitda - depreciation', isSubtotal: true },
      { key: 'interest', name: 'Interest Expense', formula: '0' },
      { key: 'ebt', name: 'Earnings Before Tax', formula: 'ebit - interest', isSubtotal: true },
      { key: 'taxes', name: 'Income Tax', formula: 'IF(ebt > 0, ebt * tax_rate / 100, 0)' },
      { key: 'net_income', name: 'Net Income', formula: 'ebt - taxes', isTotal: true },
    ],
    bs: [
      { key: 'cash', name: 'Cash & Equivalents', isTotal: true },
      { key: 'accounts_receivable', name: 'Accounts Receivable', formula: 'revenue * accounts_receivable_days / 30' },
      { key: 'inventory', name: 'Inventory', formula: 'cogs / inventory_turns * 12' },
      { key: 'total_current_assets', name: 'Total Current Assets', formula: 'cash + accounts_receivable + inventory', isSubtotal: true },
      { key: 'fixed_assets', name: 'Fixed Assets (net)', formula: '0' },
      { key: 'total_assets', name: 'Total Assets', formula: 'total_current_assets + fixed_assets', isTotal: true },
      { key: 'accounts_payable', name: 'Accounts Payable', formula: 'cogs * accounts_payable_days / 30' },
      { key: 'total_current_liabilities', name: 'Total Current Liabilities', formula: 'accounts_payable', isSubtotal: true },
      { key: 'long_term_debt', name: 'Long-Term Debt', formula: '0' },
      { key: 'total_liabilities', name: 'Total Liabilities', formula: 'total_current_liabilities + long_term_debt', isSubtotal: true },
      { key: 'retained_earnings', name: 'Retained Earnings' },
      { key: 'total_equity', name: 'Total Equity', formula: 'retained_earnings', isSubtotal: true },
      { key: 'total_liabilities_equity', name: 'Total Liabilities & Equity', formula: 'total_liabilities + total_equity', isTotal: true },
    ],
    cf: [
      { key: 'net_income_cf', name: 'Net Income', formula: 'net_income' },
      { key: 'depreciation_cf', name: 'Depreciation', formula: 'depreciation' },
      { key: 'change_ar', name: 'Change in Accounts Receivable' },
      { key: 'change_inventory', name: 'Change in Inventory' },
      { key: 'change_ap', name: 'Change in Accounts Payable' },
      { key: 'cash_from_operations', name: 'Cash from Operations', formula: 'net_income_cf + depreciation_cf - change_ar - change_inventory + change_ap', isSubtotal: true },
      { key: 'capex', name: 'Capital Expenditures', formula: '0' },
      { key: 'cash_from_investing', name: 'Cash from Investing', formula: '-capex', isSubtotal: true },
      { key: 'debt_proceeds', name: 'Debt Proceeds', formula: '0' },
      { key: 'cash_from_financing', name: 'Cash from Financing', formula: 'debt_proceeds', isSubtotal: true },
      { key: 'net_cash_change', name: 'Net Change in Cash', formula: 'cash_from_operations + cash_from_investing + cash_from_financing', isTotal: true },
      { key: 'ending_cash', name: 'Ending Cash Balance', isTotal: true },
    ],
  },
  wizardQuestions: [
    { key: 'q_orders', question: 'How many orders do you get per month?', type: 'number', targetAssumptionKey: 'monthly_orders' },
    { key: 'q_aov', question: 'What is your average order value?', type: 'currency', targetAssumptionKey: 'avg_order_value' },
    { key: 'q_cogs', question: 'What percentage of revenue goes to product cost?', type: 'percentage', targetAssumptionKey: 'cogs_pct' },
    { key: 'q_shipping', question: 'What is your average shipping cost per order?', type: 'currency', targetAssumptionKey: 'shipping_cost_per_order' },
    { key: 'q_growth', question: 'What monthly order growth do you expect?', type: 'percentage', targetAssumptionKey: 'revenue_growth_rate' },
    { key: 'q_marketing', question: 'How much do you spend on marketing per month?', type: 'currency', targetAssumptionKey: 'marketing_budget' },
    { key: 'q_cash', question: 'How much cash do you have in the bank?', type: 'currency', targetAssumptionKey: 'starting_cash' },
  ],
};
