import type { TemplateDefinition } from '@forge/shared';

export const generalTemplate: TemplateDefinition = {
  slug: 'general',
  name: 'General / Custom',
  description: 'Minimal defaults for any business type — customize all assumptions',
  category: 'SERVICES',
  assumptions: {
    beginner: [
      { key: 'monthly_revenue', name: 'Monthly Revenue', valueType: 'CURRENCY', unit: '$', default: 10000 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'cogs_pct', name: 'COGS (% of Revenue)', valueType: 'PERCENTAGE', unit: '%', default: 40 },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 3 },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 60000 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 25000 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
    ],
    standard: [
      { key: 'monthly_revenue', name: 'Monthly Revenue', valueType: 'CURRENCY', unit: '$', default: 10000 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'cogs_pct', name: 'COGS (% of Revenue)', valueType: 'PERCENTAGE', unit: '%', default: 40 },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 3 },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 60000 },
      { key: 'salary_growth_rate', name: 'Annual Salary Increase', valueType: 'PERCENTAGE', unit: '%', default: 3 },
      { key: 'new_hires_per_year', name: 'New Hires per Year', valueType: 'NUMBER', default: 1 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'marketing_budget', name: 'Monthly Marketing Budget', valueType: 'CURRENCY', unit: '$', default: 1000 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 25000 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
      { key: 'accounts_receivable_days', name: 'AR Days', valueType: 'NUMBER', default: 30 },
      { key: 'accounts_payable_days', name: 'AP Days', valueType: 'NUMBER', default: 30 },
    ],
    expert: [
      { key: 'monthly_revenue', name: 'Monthly Revenue', valueType: 'CURRENCY', unit: '$', default: 10000 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'cogs_pct', name: 'COGS (% of Revenue)', valueType: 'PERCENTAGE', unit: '%', default: 40 },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 3 },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 60000 },
      { key: 'salary_growth_rate', name: 'Annual Salary Increase', valueType: 'PERCENTAGE', unit: '%', default: 3 },
      { key: 'benefits_pct', name: 'Benefits (% of Salary)', valueType: 'PERCENTAGE', unit: '%', default: 20 },
      { key: 'new_hires_per_year', name: 'New Hires per Year', valueType: 'NUMBER', default: 1 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'marketing_budget', name: 'Monthly Marketing Budget', valueType: 'CURRENCY', unit: '$', default: 1000 },
      { key: 'rent', name: 'Monthly Rent', valueType: 'CURRENCY', unit: '$', default: 2000 },
      { key: 'insurance', name: 'Monthly Insurance', valueType: 'CURRENCY', unit: '$', default: 500 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 25000 },
      { key: 'funding_amount', name: 'Funding Amount', valueType: 'CURRENCY', unit: '$', default: 0 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
      { key: 'accounts_receivable_days', name: 'AR Days', valueType: 'NUMBER', default: 30 },
      { key: 'accounts_payable_days', name: 'AP Days', valueType: 'NUMBER', default: 30 },
      { key: 'capex_monthly', name: 'Monthly CapEx', valueType: 'CURRENCY', unit: '$', default: 0 },
      { key: 'depreciation_years', name: 'Depreciation (years)', valueType: 'NUMBER', default: 5 },
    ],
  },
  lineItems: {
    pl: [
      { key: 'revenue', name: 'Revenue', formula: 'monthly_revenue * GROWTH(1, revenue_growth_rate / 100, 60)', isTotal: true },
      { key: 'cogs', name: 'Cost of Goods Sold', formula: 'revenue * cogs_pct / 100' },
      { key: 'gross_profit', name: 'Gross Profit', formula: 'revenue - cogs', isSubtotal: true },
      { key: 'salaries', name: 'Salaries & Wages', formula: 'headcount * avg_salary / 12' },
      { key: 'marketing', name: 'Marketing', formula: 'marketing_budget' },
      { key: 'opex_other', name: 'Other Operating Expenses', formula: 'monthly_opex' },
      { key: 'total_opex', name: 'Total Operating Expenses', formula: 'salaries + marketing + opex_other', isSubtotal: true },
      { key: 'ebitda', name: 'EBITDA', formula: 'gross_profit - total_opex', isSubtotal: true },
      { key: 'depreciation', name: 'Depreciation', formula: '0' },
      { key: 'ebit', name: 'EBIT', formula: 'ebitda - depreciation', isSubtotal: true },
      { key: 'interest', name: 'Interest Expense', formula: '0' },
      { key: 'ebt', name: 'Earnings Before Tax', formula: 'ebit - interest', isSubtotal: true },
      { key: 'taxes', name: 'Income Tax', formula: 'IF(ebt > 0, ebt * tax_rate / 100, 0)' },
      { key: 'net_income', name: 'Net Income', formula: 'ebt - taxes', isTotal: true },
    ],
    bs: [
      { key: 'cash', name: 'Cash & Equivalents', isTotal: true },
      { key: 'accounts_receivable', name: 'Accounts Receivable', formula: 'revenue * accounts_receivable_days / 30' },
      { key: 'total_current_assets', name: 'Total Current Assets', formula: 'cash + accounts_receivable', isSubtotal: true },
      { key: 'fixed_assets', name: 'Fixed Assets (net)', formula: '0' },
      { key: 'total_assets', name: 'Total Assets', formula: 'total_current_assets + fixed_assets', isTotal: true },
      { key: 'accounts_payable', name: 'Accounts Payable', formula: 'cogs * accounts_payable_days / 30' },
      { key: 'total_current_liabilities', name: 'Total Current Liabilities', formula: 'accounts_payable', isSubtotal: true },
      { key: 'long_term_debt', name: 'Long-Term Debt', formula: '0' },
      { key: 'total_liabilities', name: 'Total Liabilities', formula: 'total_current_liabilities + long_term_debt', isSubtotal: true },
      { key: 'retained_earnings', name: 'Retained Earnings' },
      { key: 'total_equity', name: 'Total Equity', formula: 'retained_earnings', isSubtotal: true },
      { key: 'total_liabilities_equity', name: 'Total Liabilities & Equity', formula: 'total_liabilities + total_equity', isTotal: true },
    ],
    cf: [
      { key: 'net_income_cf', name: 'Net Income', formula: 'net_income' },
      { key: 'depreciation_cf', name: 'Depreciation', formula: 'depreciation' },
      { key: 'change_ar', name: 'Change in Accounts Receivable' },
      { key: 'change_ap', name: 'Change in Accounts Payable' },
      { key: 'cash_from_operations', name: 'Cash from Operations', formula: 'net_income_cf + depreciation_cf - change_ar + change_ap', isSubtotal: true },
      { key: 'capex', name: 'Capital Expenditures', formula: '0' },
      { key: 'cash_from_investing', name: 'Cash from Investing', formula: '-capex', isSubtotal: true },
      { key: 'debt_proceeds', name: 'Debt Proceeds', formula: '0' },
      { key: 'equity_proceeds', name: 'Equity Proceeds', formula: '0' },
      { key: 'cash_from_financing', name: 'Cash from Financing', formula: 'debt_proceeds + equity_proceeds', isSubtotal: true },
      { key: 'net_cash_change', name: 'Net Change in Cash', formula: 'cash_from_operations + cash_from_investing + cash_from_financing', isTotal: true },
      { key: 'ending_cash', name: 'Ending Cash Balance', isTotal: true },
    ],
  },
  wizardQuestions: [
    { key: 'q_revenue', question: 'What is your current monthly revenue?', type: 'currency', targetAssumptionKey: 'monthly_revenue' },
    { key: 'q_growth', question: 'What monthly growth rate do you expect?', type: 'percentage', targetAssumptionKey: 'revenue_growth_rate' },
    { key: 'q_cogs', question: 'What percentage of revenue goes to direct costs?', type: 'percentage', targetAssumptionKey: 'cogs_pct' },
    { key: 'q_team', question: 'How many people are on your team?', type: 'number', targetAssumptionKey: 'headcount' },
    { key: 'q_salary', question: 'What is the average annual salary?', type: 'currency', targetAssumptionKey: 'avg_salary' },
    { key: 'q_cash', question: 'How much cash do you have in the bank?', type: 'currency', targetAssumptionKey: 'starting_cash' },
  ],
};
