import type { TemplateDefinition } from '@forge/shared';

export const professionalServicesTemplate: TemplateDefinition = {
  slug: 'professional-services',
  name: 'Professional Services',
  description: 'Consulting, agencies, and service businesses with billable hours and utilization tracking',
  category: 'SERVICES',
  assumptions: {
    beginner: [
      { key: 'hourly_rate', name: 'Hourly Rate', valueType: 'CURRENCY', unit: '$', default: 150 },
      { key: 'billable_hours_per_week', name: 'Billable Hours/Week', valueType: 'NUMBER', default: 30 },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 3 },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 75000 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 25000 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
    ],
    standard: [
      { key: 'hourly_rate', name: 'Hourly Rate', valueType: 'CURRENCY', unit: '$', default: 150 },
      { key: 'billable_hours_per_week', name: 'Billable Hours/Week', valueType: 'NUMBER', default: 30 },
      { key: 'utilization_rate', name: 'Utilization Rate', valueType: 'PERCENTAGE', unit: '%', default: 75 },
      { key: 'headcount', name: 'Billable Staff', valueType: 'NUMBER', default: 5 },
      { key: 'non_billable_staff', name: 'Non-Billable Staff', valueType: 'NUMBER', default: 1 },
      { key: 'avg_salary', name: 'Avg Billable Salary', valueType: 'CURRENCY', unit: '$', default: 75000 },
      { key: 'admin_salary', name: 'Avg Admin Salary', valueType: 'CURRENCY', unit: '$', default: 55000 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'new_hires_per_year', name: 'New Hires per Year', valueType: 'NUMBER', default: 2 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 5000 },
      { key: 'marketing_budget', name: 'Monthly Marketing Budget', valueType: 'CURRENCY', unit: '$', default: 2000 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 50000 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
      { key: 'accounts_receivable_days', name: 'AR Days', valueType: 'NUMBER', default: 45 },
      { key: 'accounts_payable_days', name: 'AP Days', valueType: 'NUMBER', default: 30 },
    ],
    expert: [
      { key: 'hourly_rate', name: 'Hourly Rate', valueType: 'CURRENCY', unit: '$', default: 150 },
      { key: 'rate_increase_annual', name: 'Annual Rate Increase', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'billable_hours_per_week', name: 'Billable Hours/Week', valueType: 'NUMBER', default: 30 },
      { key: 'utilization_rate', name: 'Utilization Rate', valueType: 'PERCENTAGE', unit: '%', default: 75 },
      { key: 'headcount', name: 'Billable Staff', valueType: 'NUMBER', default: 5 },
      { key: 'non_billable_staff', name: 'Non-Billable Staff', valueType: 'NUMBER', default: 1 },
      { key: 'avg_salary', name: 'Avg Billable Salary', valueType: 'CURRENCY', unit: '$', default: 75000 },
      { key: 'admin_salary', name: 'Avg Admin Salary', valueType: 'CURRENCY', unit: '$', default: 55000 },
      { key: 'salary_growth_rate', name: 'Annual Salary Increase', valueType: 'PERCENTAGE', unit: '%', default: 3 },
      { key: 'benefits_pct', name: 'Benefits (% of Salary)', valueType: 'PERCENTAGE', unit: '%', default: 20 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'new_hires_per_year', name: 'New Hires per Year', valueType: 'NUMBER', default: 2 },
      { key: 'subcontractor_pct', name: 'Subcontractor (% of Rev)', valueType: 'PERCENTAGE', unit: '%', default: 10 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 5000 },
      { key: 'marketing_budget', name: 'Monthly Marketing Budget', valueType: 'CURRENCY', unit: '$', default: 2000 },
      { key: 'office_rent', name: 'Monthly Rent', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'software_tools', name: 'Monthly Software/Tools', valueType: 'CURRENCY', unit: '$', default: 1000 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 50000 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
      { key: 'accounts_receivable_days', name: 'AR Days', valueType: 'NUMBER', default: 45 },
      { key: 'accounts_payable_days', name: 'AP Days', valueType: 'NUMBER', default: 30 },
      { key: 'retainer_pct', name: 'Retainer Revenue (%)', valueType: 'PERCENTAGE', unit: '%', default: 30 },
      { key: 'project_pct', name: 'Project Revenue (%)', valueType: 'PERCENTAGE', unit: '%', default: 70 },
    ],
  },
  lineItems: {
    pl: [
      { key: 'revenue', name: 'Revenue', children: ['billable_revenue'], isTotal: true },
      { key: 'billable_revenue', name: 'Billable Revenue', formula: 'hourly_rate * billable_hours_per_week * 4.33 * headcount' },
      { key: 'cogs', name: 'Cost of Services', children: ['direct_labor', 'subcontractors'] },
      { key: 'direct_labor', name: 'Direct Labor', formula: 'headcount * avg_salary / 12' },
      { key: 'subcontractors', name: 'Subcontractors', formula: '0' },
      { key: 'gross_profit', name: 'Gross Profit', formula: 'revenue - direct_labor - subcontractors', isSubtotal: true },
      { key: 'admin_salaries', name: 'Admin Salaries', formula: 'non_billable_staff * admin_salary / 12' },
      { key: 'marketing', name: 'Marketing & BD', formula: 'marketing_budget' },
      { key: 'opex_other', name: 'Other Operating Expenses', formula: 'monthly_opex' },
      { key: 'total_opex', name: 'Total Operating Expenses', formula: 'admin_salaries + marketing + opex_other', isSubtotal: true },
      { key: 'ebitda', name: 'EBITDA', formula: 'gross_profit - total_opex', isSubtotal: true },
      { key: 'depreciation', name: 'Depreciation', formula: '0' },
      { key: 'ebit', name: 'EBIT', formula: 'ebitda - depreciation', isSubtotal: true },
      { key: 'interest', name: 'Interest Expense', formula: '0' },
      { key: 'ebt', name: 'Earnings Before Tax', formula: 'ebit - interest', isSubtotal: true },
      { key: 'taxes', name: 'Income Tax', formula: 'IF(ebt > 0, ebt * tax_rate / 100, 0)' },
      { key: 'net_income', name: 'Net Income', formula: 'ebt - taxes', isTotal: true },
    ],
    bs: [
      { key: 'cash', name: 'Cash & Equivalents', isTotal: true },
      { key: 'accounts_receivable', name: 'Accounts Receivable', formula: 'revenue * accounts_receivable_days / 30' },
      { key: 'total_current_assets', name: 'Total Current Assets', formula: 'cash + accounts_receivable', isSubtotal: true },
      { key: 'fixed_assets', name: 'Fixed Assets (net)', formula: '0' },
      { key: 'total_assets', name: 'Total Assets', formula: 'total_current_assets + fixed_assets', isTotal: true },
      { key: 'accounts_payable', name: 'Accounts Payable', formula: '(direct_labor + subcontractors) * accounts_payable_days / 30' },
      { key: 'total_current_liabilities', name: 'Total Current Liabilities', formula: 'accounts_payable', isSubtotal: true },
      { key: 'long_term_debt', name: 'Long-Term Debt', formula: '0' },
      { key: 'total_liabilities', name: 'Total Liabilities', formula: 'total_current_liabilities + long_term_debt', isSubtotal: true },
      { key: 'retained_earnings', name: 'Retained Earnings' },
      { key: 'total_equity', name: 'Total Equity', formula: 'retained_earnings', isSubtotal: true },
      { key: 'total_liabilities_equity', name: 'Total Liabilities & Equity', formula: 'total_liabilities + total_equity', isTotal: true },
    ],
    cf: [
      { key: 'net_income_cf', name: 'Net Income', formula: 'net_income' },
      { key: 'depreciation_cf', name: 'Depreciation', formula: 'depreciation' },
      { key: 'change_ar', name: 'Change in Accounts Receivable' },
      { key: 'change_ap', name: 'Change in Accounts Payable' },
      { key: 'cash_from_operations', name: 'Cash from Operations', formula: 'net_income_cf + depreciation_cf - change_ar + change_ap', isSubtotal: true },
      { key: 'capex', name: 'Capital Expenditures', formula: '0' },
      { key: 'cash_from_investing', name: 'Cash from Investing', formula: '-capex', isSubtotal: true },
      { key: 'debt_proceeds', name: 'Debt Proceeds', formula: '0' },
      { key: 'cash_from_financing', name: 'Cash from Financing', formula: 'debt_proceeds', isSubtotal: true },
      { key: 'net_cash_change', name: 'Net Change in Cash', formula: 'cash_from_operations + cash_from_investing + cash_from_financing', isTotal: true },
      { key: 'ending_cash', name: 'Ending Cash Balance', isTotal: true },
    ],
  },
  wizardQuestions: [
    { key: 'q_rate', question: 'What is your hourly billing rate?', type: 'currency', targetAssumptionKey: 'hourly_rate' },
    { key: 'q_hours', question: 'How many billable hours per week per person?', type: 'number', targetAssumptionKey: 'billable_hours_per_week' },
    { key: 'q_team', question: 'How many billable team members do you have?', type: 'number', targetAssumptionKey: 'headcount' },
    { key: 'q_salary', question: 'What is the average annual salary?', type: 'currency', targetAssumptionKey: 'avg_salary' },
    { key: 'q_growth', question: 'What monthly revenue growth do you expect?', type: 'percentage', targetAssumptionKey: 'revenue_growth_rate' },
    { key: 'q_cash', question: 'How much cash do you have in the bank?', type: 'currency', targetAssumptionKey: 'starting_cash' },
  ],
};
