import type { TemplateDefinition } from '@forge/shared';

export const saasTemplate: TemplateDefinition = {
  slug: 'saas',
  name: 'SaaS / Software',
  description: 'Subscription software with MRR, churn, CAC/LTV metrics',
  category: 'TECH',
  assumptions: {
    beginner: [
      // --- Base inputs ---
      { key: 'monthly_revenue', name: 'Monthly Revenue', valueType: 'CURRENCY', unit: '$', default: 10000, category: 'PRICING' },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 10, category: 'ACQUISITION' },
      { key: 'gross_margin', name: 'Gross Margin', valueType: 'PERCENTAGE', unit: '%', default: 80, category: 'PRICING' },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 3, category: 'COSTS' },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 80000, category: 'COSTS' },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 5000, category: 'COSTS' },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 50000, category: 'FUNDING' },
      { key: 'monthly_churn', name: 'Monthly Churn Rate', valueType: 'PERCENTAGE', unit: '%', default: 5, category: 'RETENTION' },
      { key: 'cac', name: 'Customer Acquisition Cost', valueType: 'CURRENCY', unit: '$', default: 200, category: 'ACQUISITION' },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25, category: 'COSTS' },
      // --- Calculated / derived ---
      { key: 'monthly_payroll', name: 'Monthly Payroll', valueType: 'CURRENCY', unit: '$', default: 20000, category: 'COSTS', formula: 'headcount * avg_salary / 12', dependsOn: ['headcount', 'avg_salary'] },
      { key: 'total_monthly_costs', name: 'Total Monthly Costs', valueType: 'CURRENCY', unit: '$', default: 25000, category: 'COSTS', formula: 'monthly_payroll + monthly_opex', dependsOn: ['monthly_payroll', 'monthly_opex'] },
      { key: 'gross_profit_monthly', name: 'Monthly Gross Profit', valueType: 'CURRENCY', unit: '$', default: 8000, category: 'PRICING', formula: 'monthly_revenue * gross_margin / 100', dependsOn: ['monthly_revenue', 'gross_margin'] },
      { key: 'net_monthly_income', name: 'Net Monthly Income', valueType: 'CURRENCY', unit: '$', default: -17000, category: 'PRICING', formula: 'gross_profit_monthly - total_monthly_costs', dependsOn: ['gross_profit_monthly', 'total_monthly_costs'] },
      { key: 'tax_expense_monthly', name: 'Monthly Tax Expense', valueType: 'CURRENCY', unit: '$', default: 0, category: 'COSTS', formula: 'IF(net_monthly_income > 0, net_monthly_income * tax_rate / 100, 0)', dependsOn: ['net_monthly_income', 'tax_rate'] },
      { key: 'net_income_after_tax', name: 'Net Income After Tax', valueType: 'CURRENCY', unit: '$', default: -17000, category: 'PRICING', formula: 'net_monthly_income - tax_expense_monthly', dependsOn: ['net_monthly_income', 'tax_expense_monthly'] },
      { key: 'runway_months', name: 'Runway (Months)', valueType: 'NUMBER', unit: 'months', default: 3, category: 'FUNDING', formula: 'abs(starting_cash / net_income_after_tax)', dependsOn: ['starting_cash', 'net_income_after_tax'] },
      { key: 'customer_lifetime_months', name: 'Avg Customer Lifetime', valueType: 'NUMBER', unit: 'months', default: 20, category: 'RETENTION', formula: '100 / monthly_churn', dependsOn: ['monthly_churn'] },
      { key: 'acquisition_capacity', name: 'New Customers from Profit', valueType: 'NUMBER', default: 40, category: 'ACQUISITION', formula: 'gross_profit_monthly / cac', dependsOn: ['gross_profit_monthly', 'cac'] },
      { key: 'projected_revenue_m12', name: 'Projected Revenue (Month 12)', valueType: 'CURRENCY', unit: '$', default: 31384, category: 'ACQUISITION', formula: 'monthly_revenue * (1 + revenue_growth_rate / 100) ^ 12', dependsOn: ['monthly_revenue', 'revenue_growth_rate'] },
    ],
    standard: [
      // --- Base inputs ---
      { key: 'monthly_revenue', name: 'Monthly Revenue', valueType: 'CURRENCY', unit: '$', default: 10000, category: 'PRICING' },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 10, category: 'ACQUISITION' },
      { key: 'arpu', name: 'Avg Revenue Per User', valueType: 'CURRENCY', unit: '$', default: 50, category: 'PRICING' },
      { key: 'starting_customers', name: 'Starting Customers', valueType: 'NUMBER', default: 200, category: 'MARKET' },
      { key: 'monthly_churn', name: 'Monthly Churn Rate', valueType: 'PERCENTAGE', unit: '%', default: 5, category: 'RETENTION' },
      { key: 'cac', name: 'Customer Acquisition Cost', valueType: 'CURRENCY', unit: '$', default: 200, category: 'ACQUISITION' },
      { key: 'monthly_new_customers', name: 'New Customers/Month', valueType: 'NUMBER', default: 30, category: 'ACQUISITION' },
      { key: 'gross_margin', name: 'Gross Margin', valueType: 'PERCENTAGE', unit: '%', default: 80, category: 'PRICING' },
      { key: 'hosting_cost_pct', name: 'Hosting Cost (% of Rev)', valueType: 'PERCENTAGE', unit: '%', default: 10, category: 'COSTS' },
      { key: 'support_cost_pct', name: 'Support Cost (% of Rev)', valueType: 'PERCENTAGE', unit: '%', default: 5, category: 'COSTS' },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 5, category: 'COSTS' },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 85000, category: 'COSTS' },
      { key: 'salary_growth_rate', name: 'Annual Salary Increase', valueType: 'PERCENTAGE', unit: '%', default: 3, category: 'COSTS' },
      { key: 'new_hires_per_year', name: 'New Hires per Year', valueType: 'NUMBER', default: 2, category: 'COSTS' },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 5000, category: 'COSTS' },
      { key: 'marketing_budget', name: 'Monthly Marketing Budget', valueType: 'CURRENCY', unit: '$', default: 3000, category: 'ACQUISITION' },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 100000, category: 'FUNDING' },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25, category: 'COSTS' },
      { key: 'accounts_receivable_days', name: 'AR Days', valueType: 'NUMBER', default: 30, category: 'COSTS' },
      { key: 'accounts_payable_days', name: 'AP Days', valueType: 'NUMBER', default: 45, category: 'COSTS' },
      // --- Calculated / derived ---
      { key: 'monthly_payroll', name: 'Monthly Payroll', valueType: 'CURRENCY', unit: '$', default: 35417, category: 'COSTS', formula: 'headcount * avg_salary / 12', dependsOn: ['headcount', 'avg_salary'] },
      { key: 'hosting_cost_monthly', name: 'Hosting Cost', valueType: 'CURRENCY', unit: '$', default: 1000, category: 'COSTS', formula: 'monthly_revenue * hosting_cost_pct / 100', dependsOn: ['monthly_revenue', 'hosting_cost_pct'] },
      { key: 'support_cost_monthly', name: 'Support Cost', valueType: 'CURRENCY', unit: '$', default: 500, category: 'COSTS', formula: 'monthly_revenue * support_cost_pct / 100', dependsOn: ['monthly_revenue', 'support_cost_pct'] },
      { key: 'total_monthly_costs', name: 'Total Monthly Costs', valueType: 'CURRENCY', unit: '$', default: 44917, category: 'COSTS', formula: 'monthly_payroll + monthly_opex + marketing_budget + hosting_cost_monthly + support_cost_monthly', dependsOn: ['monthly_payroll', 'monthly_opex', 'marketing_budget', 'hosting_cost_monthly', 'support_cost_monthly'] },
      { key: 'gross_profit_monthly', name: 'Monthly Gross Profit', valueType: 'CURRENCY', unit: '$', default: 8000, category: 'PRICING', formula: 'monthly_revenue * gross_margin / 100', dependsOn: ['monthly_revenue', 'gross_margin'] },
      { key: 'net_monthly_income', name: 'Net Monthly Income', valueType: 'CURRENCY', unit: '$', default: -36917, category: 'PRICING', formula: 'gross_profit_monthly - total_monthly_costs', dependsOn: ['gross_profit_monthly', 'total_monthly_costs'] },
      { key: 'tax_expense_monthly', name: 'Monthly Tax Expense', valueType: 'CURRENCY', unit: '$', default: 0, category: 'COSTS', formula: 'IF(net_monthly_income > 0, net_monthly_income * tax_rate / 100, 0)', dependsOn: ['net_monthly_income', 'tax_rate'] },
      { key: 'net_income_after_tax', name: 'Net Income After Tax', valueType: 'CURRENCY', unit: '$', default: -36917, category: 'PRICING', formula: 'net_monthly_income - tax_expense_monthly', dependsOn: ['net_monthly_income', 'tax_expense_monthly'] },
      { key: 'runway_months', name: 'Runway (Months)', valueType: 'NUMBER', unit: 'months', default: 3, category: 'FUNDING', formula: 'abs(starting_cash / net_income_after_tax)', dependsOn: ['starting_cash', 'net_income_after_tax'] },
      { key: 'ltv', name: 'Customer Lifetime Value', valueType: 'CURRENCY', unit: '$', default: 1000, category: 'RETENTION', formula: 'arpu / (monthly_churn / 100)', dependsOn: ['arpu', 'monthly_churn'] },
      { key: 'ltv_cac_ratio', name: 'LTV:CAC Ratio', valueType: 'NUMBER', unit: 'x', default: 5, category: 'ACQUISITION', formula: 'ltv / cac', dependsOn: ['ltv', 'cac'] },
      { key: 'customer_count_m1', name: 'Customers (Month 1)', valueType: 'NUMBER', default: 230, category: 'MARKET', formula: 'starting_customers + monthly_new_customers', dependsOn: ['starting_customers', 'monthly_new_customers'] },
      { key: 'projected_revenue_m12', name: 'Projected Revenue (Month 12)', valueType: 'CURRENCY', unit: '$', default: 31384, category: 'ACQUISITION', formula: 'monthly_revenue * (1 + revenue_growth_rate / 100) ^ 12', dependsOn: ['monthly_revenue', 'revenue_growth_rate'] },
      { key: 'year2_headcount', name: 'Year 2 Headcount', valueType: 'NUMBER', default: 7, category: 'COSTS', formula: 'headcount + new_hires_per_year', dependsOn: ['headcount', 'new_hires_per_year'] },
      { key: 'year2_avg_salary', name: 'Year 2 Avg Salary', valueType: 'CURRENCY', unit: '$', default: 87550, category: 'COSTS', formula: 'avg_salary * (1 + salary_growth_rate / 100)', dependsOn: ['avg_salary', 'salary_growth_rate'] },
      { key: 'accounts_receivable', name: 'Accounts Receivable', valueType: 'CURRENCY', unit: '$', default: 10000, category: 'COSTS', formula: 'monthly_revenue * accounts_receivable_days / 30', dependsOn: ['monthly_revenue', 'accounts_receivable_days'] },
      { key: 'accounts_payable', name: 'Accounts Payable', valueType: 'CURRENCY', unit: '$', default: 3000, category: 'COSTS', formula: 'total_monthly_costs * accounts_payable_days / 30', dependsOn: ['total_monthly_costs', 'accounts_payable_days'] },
      { key: 'working_capital', name: 'Working Capital', valueType: 'CURRENCY', unit: '$', default: 7000, category: 'FUNDING', formula: 'accounts_receivable - accounts_payable', dependsOn: ['accounts_receivable', 'accounts_payable'] },
    ],
    expert: [
      // --- Base inputs ---
      { key: 'monthly_revenue', name: 'Monthly Revenue', valueType: 'CURRENCY', unit: '$', default: 10000, category: 'PRICING' },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 10, category: 'ACQUISITION' },
      { key: 'arpu', name: 'Avg Revenue Per User', valueType: 'CURRENCY', unit: '$', default: 50, category: 'PRICING' },
      { key: 'starting_customers', name: 'Starting Customers', valueType: 'NUMBER', default: 200, category: 'MARKET' },
      { key: 'monthly_churn', name: 'Monthly Churn Rate', valueType: 'PERCENTAGE', unit: '%', default: 5, category: 'RETENTION' },
      { key: 'expansion_revenue_rate', name: 'Net Revenue Expansion', valueType: 'PERCENTAGE', unit: '%', default: 2, category: 'RETENTION' },
      { key: 'cac', name: 'Customer Acquisition Cost', valueType: 'CURRENCY', unit: '$', default: 200, category: 'ACQUISITION' },
      { key: 'monthly_new_customers', name: 'New Customers/Month', valueType: 'NUMBER', default: 30, category: 'ACQUISITION' },
      { key: 'gross_margin', name: 'Gross Margin', valueType: 'PERCENTAGE', unit: '%', default: 80, category: 'PRICING' },
      { key: 'hosting_cost_pct', name: 'Hosting Cost (% of Rev)', valueType: 'PERCENTAGE', unit: '%', default: 10, category: 'COSTS' },
      { key: 'support_cost_pct', name: 'Support Cost (% of Rev)', valueType: 'PERCENTAGE', unit: '%', default: 5, category: 'COSTS' },
      { key: 'payment_processing_pct', name: 'Payment Processing (%)', valueType: 'PERCENTAGE', unit: '%', default: 2.9, category: 'COSTS' },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 5, category: 'COSTS' },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 85000, category: 'COSTS' },
      { key: 'salary_growth_rate', name: 'Annual Salary Increase', valueType: 'PERCENTAGE', unit: '%', default: 3, category: 'COSTS' },
      { key: 'new_hires_per_year', name: 'New Hires per Year', valueType: 'NUMBER', default: 2, category: 'COSTS' },
      { key: 'benefits_pct', name: 'Benefits (% of Salary)', valueType: 'PERCENTAGE', unit: '%', default: 20, category: 'COSTS' },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 5000, category: 'COSTS' },
      { key: 'marketing_budget', name: 'Monthly Marketing Budget', valueType: 'CURRENCY', unit: '$', default: 3000, category: 'ACQUISITION' },
      { key: 'rd_spend_pct', name: 'R&D Spend (% of Rev)', valueType: 'PERCENTAGE', unit: '%', default: 15, category: 'COSTS' },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 100000, category: 'FUNDING' },
      { key: 'funding_amount', name: 'Funding Amount', valueType: 'CURRENCY', unit: '$', default: 0, category: 'FUNDING' },
      { key: 'funding_month', name: 'Funding Month', valueType: 'NUMBER', default: 0, category: 'FUNDING' },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25, category: 'COSTS' },
      { key: 'accounts_receivable_days', name: 'AR Days', valueType: 'NUMBER', default: 30, category: 'COSTS' },
      { key: 'accounts_payable_days', name: 'AP Days', valueType: 'NUMBER', default: 45, category: 'COSTS' },
      { key: 'deferred_revenue_months', name: 'Deferred Revenue (months)', valueType: 'NUMBER', default: 1, category: 'COSTS' },
      { key: 'capex_monthly', name: 'Monthly CapEx', valueType: 'CURRENCY', unit: '$', default: 0, category: 'COSTS' },
      { key: 'depreciation_years', name: 'Depreciation (years)', valueType: 'NUMBER', default: 3, category: 'COSTS' },
      // --- Calculated / derived ---
      { key: 'monthly_payroll', name: 'Monthly Payroll', valueType: 'CURRENCY', unit: '$', default: 35417, category: 'COSTS', formula: 'headcount * avg_salary / 12', dependsOn: ['headcount', 'avg_salary'] },
      { key: 'total_people_cost', name: 'Total People Cost', valueType: 'CURRENCY', unit: '$', default: 42500, category: 'COSTS', formula: 'monthly_payroll * (1 + benefits_pct / 100)', dependsOn: ['monthly_payroll', 'benefits_pct'] },
      { key: 'hosting_cost_monthly', name: 'Hosting Cost', valueType: 'CURRENCY', unit: '$', default: 1000, category: 'COSTS', formula: 'monthly_revenue * hosting_cost_pct / 100', dependsOn: ['monthly_revenue', 'hosting_cost_pct'] },
      { key: 'support_cost_monthly', name: 'Support Cost', valueType: 'CURRENCY', unit: '$', default: 500, category: 'COSTS', formula: 'monthly_revenue * support_cost_pct / 100', dependsOn: ['monthly_revenue', 'support_cost_pct'] },
      { key: 'payment_processing_monthly', name: 'Payment Processing', valueType: 'CURRENCY', unit: '$', default: 290, category: 'COSTS', formula: 'monthly_revenue * payment_processing_pct / 100', dependsOn: ['monthly_revenue', 'payment_processing_pct'] },
      { key: 'rd_spend_monthly', name: 'R&D Spend', valueType: 'CURRENCY', unit: '$', default: 1500, category: 'COSTS', formula: 'monthly_revenue * rd_spend_pct / 100', dependsOn: ['monthly_revenue', 'rd_spend_pct'] },
      { key: 'total_monthly_costs', name: 'Total Monthly Costs', valueType: 'CURRENCY', unit: '$', default: 53790, category: 'COSTS', formula: 'total_people_cost + monthly_opex + marketing_budget + hosting_cost_monthly + support_cost_monthly + payment_processing_monthly + rd_spend_monthly', dependsOn: ['total_people_cost', 'monthly_opex', 'marketing_budget', 'hosting_cost_monthly', 'support_cost_monthly', 'payment_processing_monthly', 'rd_spend_monthly'] },
      { key: 'gross_profit_monthly', name: 'Monthly Gross Profit', valueType: 'CURRENCY', unit: '$', default: 8000, category: 'PRICING', formula: 'monthly_revenue * gross_margin / 100', dependsOn: ['monthly_revenue', 'gross_margin'] },
      { key: 'net_monthly_income', name: 'Net Monthly Income', valueType: 'CURRENCY', unit: '$', default: -45790, category: 'PRICING', formula: 'gross_profit_monthly - total_monthly_costs', dependsOn: ['gross_profit_monthly', 'total_monthly_costs'] },
      { key: 'tax_expense_monthly', name: 'Monthly Tax Expense', valueType: 'CURRENCY', unit: '$', default: 0, category: 'COSTS', formula: 'IF(net_monthly_income > 0, net_monthly_income * tax_rate / 100, 0)', dependsOn: ['net_monthly_income', 'tax_rate'] },
      { key: 'net_income_after_tax', name: 'Net Income After Tax', valueType: 'CURRENCY', unit: '$', default: -45790, category: 'PRICING', formula: 'net_monthly_income - tax_expense_monthly', dependsOn: ['net_monthly_income', 'tax_expense_monthly'] },
      { key: 'total_available_cash', name: 'Total Available Cash', valueType: 'CURRENCY', unit: '$', default: 100000, category: 'FUNDING', formula: 'starting_cash + IF(funding_month > 0, funding_amount, 0)', dependsOn: ['starting_cash', 'funding_month', 'funding_amount'] },
      { key: 'runway_months', name: 'Runway (Months)', valueType: 'NUMBER', unit: 'months', default: 2, category: 'FUNDING', formula: 'abs(total_available_cash / net_income_after_tax)', dependsOn: ['total_available_cash', 'net_income_after_tax'] },
      { key: 'ltv', name: 'Customer Lifetime Value', valueType: 'CURRENCY', unit: '$', default: 1000, category: 'RETENTION', formula: 'arpu / (monthly_churn / 100)', dependsOn: ['arpu', 'monthly_churn'] },
      { key: 'ltv_cac_ratio', name: 'LTV:CAC Ratio', valueType: 'NUMBER', unit: 'x', default: 5, category: 'ACQUISITION', formula: 'ltv / cac', dependsOn: ['ltv', 'cac'] },
      { key: 'net_revenue_retention', name: 'Net Revenue Retention', valueType: 'PERCENTAGE', unit: '%', default: 97, category: 'RETENTION', formula: '100 - monthly_churn + expansion_revenue_rate', dependsOn: ['monthly_churn', 'expansion_revenue_rate'] },
      { key: 'customer_count_m1', name: 'Customers (Month 1)', valueType: 'NUMBER', default: 230, category: 'MARKET', formula: 'starting_customers + monthly_new_customers', dependsOn: ['starting_customers', 'monthly_new_customers'] },
      { key: 'projected_revenue_m12', name: 'Projected Revenue (Month 12)', valueType: 'CURRENCY', unit: '$', default: 31384, category: 'ACQUISITION', formula: 'monthly_revenue * (1 + revenue_growth_rate / 100) ^ 12', dependsOn: ['monthly_revenue', 'revenue_growth_rate'] },
      { key: 'year2_headcount', name: 'Year 2 Headcount', valueType: 'NUMBER', default: 7, category: 'COSTS', formula: 'headcount + new_hires_per_year', dependsOn: ['headcount', 'new_hires_per_year'] },
      { key: 'year2_avg_salary', name: 'Year 2 Avg Salary', valueType: 'CURRENCY', unit: '$', default: 87550, category: 'COSTS', formula: 'avg_salary * (1 + salary_growth_rate / 100)', dependsOn: ['avg_salary', 'salary_growth_rate'] },
      { key: 'accounts_receivable', name: 'Accounts Receivable', valueType: 'CURRENCY', unit: '$', default: 10000, category: 'COSTS', formula: 'monthly_revenue * accounts_receivable_days / 30', dependsOn: ['monthly_revenue', 'accounts_receivable_days'] },
      { key: 'accounts_payable', name: 'Accounts Payable', valueType: 'CURRENCY', unit: '$', default: 80685, category: 'COSTS', formula: 'total_monthly_costs * accounts_payable_days / 30', dependsOn: ['total_monthly_costs', 'accounts_payable_days'] },
      { key: 'deferred_revenue_balance', name: 'Deferred Revenue', valueType: 'CURRENCY', unit: '$', default: 10000, category: 'COSTS', formula: 'monthly_revenue * deferred_revenue_months', dependsOn: ['monthly_revenue', 'deferred_revenue_months'] },
      { key: 'working_capital', name: 'Working Capital', valueType: 'CURRENCY', unit: '$', default: -80685, category: 'FUNDING', formula: 'accounts_receivable - accounts_payable - deferred_revenue_balance', dependsOn: ['accounts_receivable', 'accounts_payable', 'deferred_revenue_balance'] },
      { key: 'monthly_depreciation', name: 'Monthly Depreciation', valueType: 'CURRENCY', unit: '$', default: 0, category: 'COSTS', formula: 'IF(depreciation_years > 0, capex_monthly / (depreciation_years * 12), 0)', dependsOn: ['capex_monthly', 'depreciation_years'] },
    ],
  },
  lineItems: {
    pl: [
      { key: 'revenue', name: 'Revenue', children: ['subscription_revenue', 'services_revenue'], isTotal: true },
      { key: 'subscription_revenue', name: 'Subscription Revenue', formula: 'monthly_revenue * GROWTH(1, revenue_growth_rate / 100, 60)' },
      { key: 'services_revenue', name: 'Services Revenue', formula: '0' },
      { key: 'cogs', name: 'Cost of Goods Sold', formula: 'revenue * (1 - gross_margin / 100)' },
      { key: 'gross_profit', name: 'Gross Profit', formula: 'revenue - cogs', isSubtotal: true },
      { key: 'salaries', name: 'Salaries & Wages', formula: 'headcount * avg_salary / 12' },
      { key: 'marketing', name: 'Marketing & Sales', formula: 'marketing_budget' },
      { key: 'opex_other', name: 'Other Operating Expenses', formula: 'monthly_opex' },
      { key: 'total_opex', name: 'Total Operating Expenses', formula: 'salaries + marketing + opex_other', isSubtotal: true },
      { key: 'ebitda', name: 'EBITDA', formula: 'gross_profit - total_opex', isSubtotal: true },
      { key: 'depreciation', name: 'Depreciation & Amortization', formula: '0' },
      { key: 'ebit', name: 'EBIT', formula: 'ebitda - depreciation', isSubtotal: true },
      { key: 'interest', name: 'Interest Expense', formula: '0' },
      { key: 'ebt', name: 'Earnings Before Tax', formula: 'ebit - interest', isSubtotal: true },
      { key: 'taxes', name: 'Income Tax', formula: 'IF(ebt > 0, ebt * tax_rate / 100, 0)' },
      { key: 'net_income', name: 'Net Income', formula: 'ebt - taxes', isTotal: true },
    ],
    bs: [
      { key: 'cash', name: 'Cash & Equivalents', isTotal: true },
      { key: 'accounts_receivable', name: 'Accounts Receivable', formula: 'revenue * accounts_receivable_days / 30' },
      { key: 'total_current_assets', name: 'Total Current Assets', formula: 'cash + accounts_receivable', isSubtotal: true },
      { key: 'fixed_assets', name: 'Fixed Assets (net)', formula: '0' },
      { key: 'total_assets', name: 'Total Assets', formula: 'total_current_assets + fixed_assets', isTotal: true },
      { key: 'accounts_payable', name: 'Accounts Payable', formula: 'cogs * accounts_payable_days / 30' },
      { key: 'deferred_revenue', name: 'Deferred Revenue', formula: '0' },
      { key: 'total_current_liabilities', name: 'Total Current Liabilities', formula: 'accounts_payable + deferred_revenue', isSubtotal: true },
      { key: 'long_term_debt', name: 'Long-Term Debt', formula: '0' },
      { key: 'total_liabilities', name: 'Total Liabilities', formula: 'total_current_liabilities + long_term_debt', isSubtotal: true },
      { key: 'retained_earnings', name: 'Retained Earnings' },
      { key: 'total_equity', name: 'Total Equity', formula: 'retained_earnings', isSubtotal: true },
      { key: 'total_liabilities_equity', name: 'Total Liabilities & Equity', formula: 'total_liabilities + total_equity', isTotal: true },
    ],
    cf: [
      { key: 'net_income_cf', name: 'Net Income', formula: 'net_income' },
      { key: 'depreciation_cf', name: 'Depreciation & Amortization', formula: 'depreciation' },
      { key: 'change_ar', name: 'Change in Accounts Receivable' },
      { key: 'change_ap', name: 'Change in Accounts Payable' },
      { key: 'change_deferred_rev', name: 'Change in Deferred Revenue' },
      { key: 'cash_from_operations', name: 'Cash from Operations', formula: 'net_income_cf + depreciation_cf - change_ar + change_ap + change_deferred_rev', isSubtotal: true },
      { key: 'capex', name: 'Capital Expenditures', formula: '0' },
      { key: 'cash_from_investing', name: 'Cash from Investing', formula: '-capex', isSubtotal: true },
      { key: 'debt_proceeds', name: 'Debt Proceeds', formula: '0' },
      { key: 'equity_proceeds', name: 'Equity Proceeds', formula: '0' },
      { key: 'cash_from_financing', name: 'Cash from Financing', formula: 'debt_proceeds + equity_proceeds', isSubtotal: true },
      { key: 'net_cash_change', name: 'Net Change in Cash', formula: 'cash_from_operations + cash_from_investing + cash_from_financing', isTotal: true },
      { key: 'ending_cash', name: 'Ending Cash Balance', isTotal: true },
    ],
  },
  wizardQuestions: [
    { key: 'q_revenue', question: 'What is your current monthly revenue?', type: 'currency', targetAssumptionKey: 'monthly_revenue' },
    { key: 'q_growth', question: 'How fast are you growing month-over-month?', type: 'percentage', targetAssumptionKey: 'revenue_growth_rate' },
    { key: 'q_margin', question: 'What is your gross margin?', type: 'percentage', targetAssumptionKey: 'gross_margin' },
    { key: 'q_team', question: 'How many people are on your team?', type: 'number', targetAssumptionKey: 'headcount' },
    { key: 'q_salary', question: 'What is the average annual salary?', type: 'currency', targetAssumptionKey: 'avg_salary' },
    { key: 'q_churn', question: 'What is your monthly customer churn rate?', type: 'percentage', targetAssumptionKey: 'monthly_churn' },
    { key: 'q_cac', question: 'How much does it cost to acquire a customer?', type: 'currency', targetAssumptionKey: 'cac' },
    { key: 'q_cash', question: 'How much cash do you have in the bank?', type: 'currency', targetAssumptionKey: 'starting_cash' },
  ],
};
