import type { TemplateDefinition } from '@forge/shared';

export const saasTemplate: TemplateDefinition = {
  slug: 'saas',
  name: 'SaaS / Software',
  description: 'Subscription software with MRR, churn, CAC/LTV metrics',
  category: 'TECH',
  assumptions: {
    beginner: [
      { key: 'monthly_revenue', name: 'Monthly Revenue', valueType: 'CURRENCY', unit: '$', default: 10000 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 10 },
      { key: 'gross_margin', name: 'Gross Margin', valueType: 'PERCENTAGE', unit: '%', default: 80 },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 3 },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 80000 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 5000 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 50000 },
      { key: 'monthly_churn', name: 'Monthly Churn Rate', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'cac', name: 'Customer Acquisition Cost', valueType: 'CURRENCY', unit: '$', default: 200 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
    ],
    standard: [
      { key: 'monthly_revenue', name: 'Monthly Revenue', valueType: 'CURRENCY', unit: '$', default: 10000 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 10 },
      { key: 'arpu', name: 'Avg Revenue Per User', valueType: 'CURRENCY', unit: '$', default: 50 },
      { key: 'starting_customers', name: 'Starting Customers', valueType: 'NUMBER', default: 200 },
      { key: 'monthly_churn', name: 'Monthly Churn Rate', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'cac', name: 'Customer Acquisition Cost', valueType: 'CURRENCY', unit: '$', default: 200 },
      { key: 'monthly_new_customers', name: 'New Customers/Month', valueType: 'NUMBER', default: 30 },
      { key: 'gross_margin', name: 'Gross Margin', valueType: 'PERCENTAGE', unit: '%', default: 80 },
      { key: 'hosting_cost_pct', name: 'Hosting Cost (% of Rev)', valueType: 'PERCENTAGE', unit: '%', default: 10 },
      { key: 'support_cost_pct', name: 'Support Cost (% of Rev)', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 5 },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 85000 },
      { key: 'salary_growth_rate', name: 'Annual Salary Increase', valueType: 'PERCENTAGE', unit: '%', default: 3 },
      { key: 'new_hires_per_year', name: 'New Hires per Year', valueType: 'NUMBER', default: 2 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 5000 },
      { key: 'marketing_budget', name: 'Monthly Marketing Budget', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 100000 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
      { key: 'accounts_receivable_days', name: 'AR Days', valueType: 'NUMBER', default: 30 },
      { key: 'accounts_payable_days', name: 'AP Days', valueType: 'NUMBER', default: 45 },
    ],
    expert: [
      { key: 'monthly_revenue', name: 'Monthly Revenue', valueType: 'CURRENCY', unit: '$', default: 10000 },
      { key: 'revenue_growth_rate', name: 'Monthly Growth Rate', valueType: 'PERCENTAGE', unit: '%', default: 10 },
      { key: 'arpu', name: 'Avg Revenue Per User', valueType: 'CURRENCY', unit: '$', default: 50 },
      { key: 'starting_customers', name: 'Starting Customers', valueType: 'NUMBER', default: 200 },
      { key: 'monthly_churn', name: 'Monthly Churn Rate', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'expansion_revenue_rate', name: 'Net Revenue Expansion', valueType: 'PERCENTAGE', unit: '%', default: 2 },
      { key: 'cac', name: 'Customer Acquisition Cost', valueType: 'CURRENCY', unit: '$', default: 200 },
      { key: 'monthly_new_customers', name: 'New Customers/Month', valueType: 'NUMBER', default: 30 },
      { key: 'gross_margin', name: 'Gross Margin', valueType: 'PERCENTAGE', unit: '%', default: 80 },
      { key: 'hosting_cost_pct', name: 'Hosting Cost (% of Rev)', valueType: 'PERCENTAGE', unit: '%', default: 10 },
      { key: 'support_cost_pct', name: 'Support Cost (% of Rev)', valueType: 'PERCENTAGE', unit: '%', default: 5 },
      { key: 'payment_processing_pct', name: 'Payment Processing (%)', valueType: 'PERCENTAGE', unit: '%', default: 2.9 },
      { key: 'headcount', name: 'Team Size', valueType: 'NUMBER', default: 5 },
      { key: 'avg_salary', name: 'Average Annual Salary', valueType: 'CURRENCY', unit: '$', default: 85000 },
      { key: 'salary_growth_rate', name: 'Annual Salary Increase', valueType: 'PERCENTAGE', unit: '%', default: 3 },
      { key: 'new_hires_per_year', name: 'New Hires per Year', valueType: 'NUMBER', default: 2 },
      { key: 'benefits_pct', name: 'Benefits (% of Salary)', valueType: 'PERCENTAGE', unit: '%', default: 20 },
      { key: 'monthly_opex', name: 'Monthly Operating Expenses', valueType: 'CURRENCY', unit: '$', default: 5000 },
      { key: 'marketing_budget', name: 'Monthly Marketing Budget', valueType: 'CURRENCY', unit: '$', default: 3000 },
      { key: 'rd_spend_pct', name: 'R&D Spend (% of Rev)', valueType: 'PERCENTAGE', unit: '%', default: 15 },
      { key: 'starting_cash', name: 'Starting Cash', valueType: 'CURRENCY', unit: '$', default: 100000 },
      { key: 'funding_amount', name: 'Funding Amount', valueType: 'CURRENCY', unit: '$', default: 0 },
      { key: 'funding_month', name: 'Funding Month', valueType: 'NUMBER', default: 0 },
      { key: 'tax_rate', name: 'Tax Rate', valueType: 'PERCENTAGE', unit: '%', default: 25 },
      { key: 'accounts_receivable_days', name: 'AR Days', valueType: 'NUMBER', default: 30 },
      { key: 'accounts_payable_days', name: 'AP Days', valueType: 'NUMBER', default: 45 },
      { key: 'deferred_revenue_months', name: 'Deferred Revenue (months)', valueType: 'NUMBER', default: 1 },
      { key: 'capex_monthly', name: 'Monthly CapEx', valueType: 'CURRENCY', unit: '$', default: 0 },
      { key: 'depreciation_years', name: 'Depreciation (years)', valueType: 'NUMBER', default: 3 },
      { key: 'ltv_cac_target', name: 'LTV/CAC Target', valueType: 'NUMBER', default: 3, formula: '(arpu / monthly_churn * 100) / cac', dependsOn: ['arpu', 'monthly_churn', 'cac'], category: 'ACQUISITION' },
    ],
  },
  lineItems: {
    pl: [
      { key: 'revenue', name: 'Revenue', children: ['subscription_revenue', 'services_revenue'], isTotal: true },
      { key: 'subscription_revenue', name: 'Subscription Revenue', formula: 'monthly_revenue * GROWTH(1, revenue_growth_rate / 100, 60)' },
      { key: 'services_revenue', name: 'Services Revenue', formula: '0' },
      { key: 'cogs', name: 'Cost of Goods Sold', formula: 'revenue * (1 - gross_margin / 100)' },
      { key: 'gross_profit', name: 'Gross Profit', formula: 'revenue - cogs', isSubtotal: true },
      { key: 'salaries', name: 'Salaries & Wages', formula: 'headcount * avg_salary / 12' },
      { key: 'marketing', name: 'Marketing & Sales', formula: 'marketing_budget' },
      { key: 'opex_other', name: 'Other Operating Expenses', formula: 'monthly_opex' },
      { key: 'total_opex', name: 'Total Operating Expenses', formula: 'salaries + marketing + opex_other', isSubtotal: true },
      { key: 'ebitda', name: 'EBITDA', formula: 'gross_profit - total_opex', isSubtotal: true },
      { key: 'depreciation', name: 'Depreciation & Amortization', formula: '0' },
      { key: 'ebit', name: 'EBIT', formula: 'ebitda - depreciation', isSubtotal: true },
      { key: 'interest', name: 'Interest Expense', formula: '0' },
      { key: 'ebt', name: 'Earnings Before Tax', formula: 'ebit - interest', isSubtotal: true },
      { key: 'taxes', name: 'Income Tax', formula: 'IF(ebt > 0, ebt * tax_rate / 100, 0)' },
      { key: 'net_income', name: 'Net Income', formula: 'ebt - taxes', isTotal: true },
    ],
    bs: [
      { key: 'cash', name: 'Cash & Equivalents', isTotal: true },
      { key: 'accounts_receivable', name: 'Accounts Receivable', formula: 'revenue * accounts_receivable_days / 30' },
      { key: 'total_current_assets', name: 'Total Current Assets', formula: 'cash + accounts_receivable', isSubtotal: true },
      { key: 'fixed_assets', name: 'Fixed Assets (net)', formula: '0' },
      { key: 'total_assets', name: 'Total Assets', formula: 'total_current_assets + fixed_assets', isTotal: true },
      { key: 'accounts_payable', name: 'Accounts Payable', formula: 'cogs * accounts_payable_days / 30' },
      { key: 'deferred_revenue', name: 'Deferred Revenue', formula: '0' },
      { key: 'total_current_liabilities', name: 'Total Current Liabilities', formula: 'accounts_payable + deferred_revenue', isSubtotal: true },
      { key: 'long_term_debt', name: 'Long-Term Debt', formula: '0' },
      { key: 'total_liabilities', name: 'Total Liabilities', formula: 'total_current_liabilities + long_term_debt', isSubtotal: true },
      { key: 'retained_earnings', name: 'Retained Earnings' },
      { key: 'total_equity', name: 'Total Equity', formula: 'retained_earnings', isSubtotal: true },
      { key: 'total_liabilities_equity', name: 'Total Liabilities & Equity', formula: 'total_liabilities + total_equity', isTotal: true },
    ],
    cf: [
      { key: 'net_income_cf', name: 'Net Income', formula: 'net_income' },
      { key: 'depreciation_cf', name: 'Depreciation & Amortization', formula: 'depreciation' },
      { key: 'change_ar', name: 'Change in Accounts Receivable' },
      { key: 'change_ap', name: 'Change in Accounts Payable' },
      { key: 'change_deferred_rev', name: 'Change in Deferred Revenue' },
      { key: 'cash_from_operations', name: 'Cash from Operations', formula: 'net_income_cf + depreciation_cf - change_ar + change_ap + change_deferred_rev', isSubtotal: true },
      { key: 'capex', name: 'Capital Expenditures', formula: '0' },
      { key: 'cash_from_investing', name: 'Cash from Investing', formula: '-capex', isSubtotal: true },
      { key: 'debt_proceeds', name: 'Debt Proceeds', formula: '0' },
      { key: 'equity_proceeds', name: 'Equity Proceeds', formula: '0' },
      { key: 'cash_from_financing', name: 'Cash from Financing', formula: 'debt_proceeds + equity_proceeds', isSubtotal: true },
      { key: 'net_cash_change', name: 'Net Change in Cash', formula: 'cash_from_operations + cash_from_investing + cash_from_financing', isTotal: true },
      { key: 'ending_cash', name: 'Ending Cash Balance', isTotal: true },
    ],
  },
  wizardQuestions: [
    { key: 'q_revenue', question: 'What is your current monthly revenue?', type: 'currency', targetAssumptionKey: 'monthly_revenue' },
    { key: 'q_growth', question: 'How fast are you growing month-over-month?', type: 'percentage', targetAssumptionKey: 'revenue_growth_rate' },
    { key: 'q_margin', question: 'What is your gross margin?', type: 'percentage', targetAssumptionKey: 'gross_margin' },
    { key: 'q_team', question: 'How many people are on your team?', type: 'number', targetAssumptionKey: 'headcount' },
    { key: 'q_salary', question: 'What is the average annual salary?', type: 'currency', targetAssumptionKey: 'avg_salary' },
    { key: 'q_churn', question: 'What is your monthly customer churn rate?', type: 'percentage', targetAssumptionKey: 'monthly_churn' },
    { key: 'q_cac', question: 'How much does it cost to acquire a customer?', type: 'currency', targetAssumptionKey: 'cac' },
    { key: 'q_cash', question: 'How much cash do you have in the bank?', type: 'currency', targetAssumptionKey: 'starting_cash' },
  ],
};
